/* Bundled catalog: well-known movies & TV shows used for the swipe deck
   and recommendation candidates when no other data source is available.
   Fields: t=title, y=year, k='m' (movie) | 'tv', g=genres[], d=director/creator */
const CATALOG = [
{t:"Top Gun: Maverick",y:2022,k:"m",g:["Action","Drama"],d:"Joseph Kosinski"},
{t:"Mad Max: Fury Road",y:2015,k:"m",g:["Action","Adventure","Sci-Fi"],d:"George Miller"},
{t:"John Wick: Chapter 4",y:2023,k:"m",g:["Action","Thriller","Crime"],d:"Chad Stahelski"},
{t:"John Wick",y:2014,k:"m",g:["Action","Thriller","Crime"],d:"Chad Stahelski"},
{t:"The Batman",y:2022,k:"m",g:["Crime","Mystery","Thriller"],d:"Matt Reeves"},
{t:"Dune: Part Two",y:2024,k:"m",g:["Sci-Fi","Adventure"],d:"Denis Villeneuve"},
{t:"Dune",y:2021,k:"m",g:["Sci-Fi","Adventure"],d:"Denis Villeneuve"},
{t:"Avatar: The Way of Water",y:2022,k:"m",g:["Sci-Fi","Adventure","Action"],d:"James Cameron"},
{t:"Godzilla Minus One",y:2023,k:"m",g:["Action","Drama","Sci-Fi"],d:"Takashi Yamazaki"},
{t:"1917",y:2019,k:"m",g:["War","Drama","History"],d:"Sam Mendes"},
{t:"Dunkirk",y:2017,k:"m",g:["War","Drama","Action"],d:"Christopher Nolan"},
{t:"Saving Private Ryan",y:1998,k:"m",g:["War","Drama","History"],d:"Steven Spielberg"},
{t:"Hacksaw Ridge",y:2016,k:"m",g:["War","Drama","History"],d:"Mel Gibson"},
{t:"Braveheart",y:1995,k:"m",g:["War","Drama","History"],d:"Mel Gibson"},
{t:"Gladiator",y:2000,k:"m",g:["Action","Adventure","Drama"],d:"Ridley Scott"},
{t:"Black Hawk Down",y:2001,k:"m",g:["War","Drama","History"],d:"Ridley Scott"},
{t:"13 Hours",y:2016,k:"m",g:["War","Action","Drama"],d:"Michael Bay"},
{t:"Lone Survivor",y:2013,k:"m",g:["War","Action","Drama"],d:"Peter Berg"},
{t:"American Sniper",y:2014,k:"m",g:["War","Drama"],d:"Clint Eastwood"},
{t:"All Quiet on the Western Front",y:2022,k:"m",g:["War","Drama","History"],d:"Edward Berger"},
{t:"Devotion",y:2022,k:"m",g:["War","Drama","Action"],d:"J.D. Dillard"},
{t:"Oppenheimer",y:2023,k:"m",g:["Drama","History","Thriller"],d:"Christopher Nolan"},
{t:"Ford v Ferrari",y:2019,k:"m",g:["Action","Drama","Sport"],d:"James Mangold"},
{t:"The Imitation Game",y:2014,k:"m",g:["Drama","History","Thriller"],d:"Morten Tyldum"},
{t:"Darkest Hour",y:2017,k:"m",g:["Drama","History","War"],d:"Joe Wright"},
{t:"The Martian",y:2015,k:"m",g:["Sci-Fi","Drama","Adventure"],d:"Ridley Scott"},
{t:"Interstellar",y:2014,k:"m",g:["Sci-Fi","Drama","Adventure"],d:"Christopher Nolan"},
{t:"Arrival",y:2016,k:"m",g:["Sci-Fi","Drama","Mystery"],d:"Denis Villeneuve"},
{t:"Blade Runner 2049",y:2017,k:"m",g:["Sci-Fi","Drama"],d:"Denis Villeneuve"},
{t:"Ex Machina",y:2014,k:"m",g:["Sci-Fi","Drama"],d:"Alex Garland"},
{t:"Edge of Tomorrow",y:2014,k:"m",g:["Action","Sci-Fi"],d:"Doug Liman"},
{t:"Inception",y:2010,k:"m",g:["Action","Sci-Fi","Thriller"],d:"Christopher Nolan"},
{t:"Gravity",y:2013,k:"m",g:["Sci-Fi","Drama","Thriller"],d:"Alfonso Cuarón"},
{t:"Ad Astra",y:2019,k:"m",g:["Sci-Fi","Drama","Adventure"],d:"James Gray"},
{t:"District 9",y:2009,k:"m",g:["Sci-Fi","Action"],d:"Neill Blomkamp"},
{t:"Children of Men",y:2006,k:"m",g:["Sci-Fi","Drama","Thriller"],d:"Alfonso Cuarón"},
{t:"Moon",y:2009,k:"m",g:["Sci-Fi","Drama","Mystery"],d:"Duncan Jones"},
{t:"Sunshine",y:2007,k:"m",g:["Sci-Fi","Thriller","Adventure"],d:"Danny Boyle"},
{t:"The Creator",y:2023,k:"m",g:["Sci-Fi","Action","Drama"],d:"Gareth Edwards"},
{t:"Prey",y:2022,k:"m",g:["Sci-Fi","Action","Thriller"],d:"Dan Trachtenberg"},
{t:"Predator",y:1987,k:"m",g:["Sci-Fi","Action","Horror"],d:"John McTiernan"},
{t:"Alien",y:1979,k:"m",g:["Horror","Sci-Fi"],d:"Ridley Scott"},
{t:"Aliens",y:1986,k:"m",g:["Action","Sci-Fi","Thriller"],d:"James Cameron"},
{t:"The Thing",y:1982,k:"m",g:["Horror","Sci-Fi","Mystery"],d:"John Carpenter"},
{t:"Get Out",y:2017,k:"m",g:["Horror","Mystery","Thriller"],d:"Jordan Peele"},
{t:"Nope",y:2022,k:"m",g:["Horror","Sci-Fi","Mystery"],d:"Jordan Peele"},
{t:"Hereditary",y:2018,k:"m",g:["Horror","Drama","Mystery"],d:"Ari Aster"},
{t:"A Quiet Place",y:2018,k:"m",g:["Horror","Drama","Sci-Fi"],d:"John Krasinski"},
{t:"28 Days Later",y:2002,k:"m",g:["Horror","Sci-Fi","Thriller"],d:"Danny Boyle"},
{t:"Train to Busan",y:2016,k:"m",g:["Horror","Action","Drama"],d:"Yeon Sang-ho"},
{t:"Sinners",y:2025,k:"m",g:["Horror","Drama","Music"],d:"Ryan Coogler"},
{t:"Weapons",y:2025,k:"m",g:["Horror","Mystery"],d:"Zach Cregger"},
{t:"Talk to Me",y:2022,k:"m",g:["Horror","Thriller"],d:"Danny Philippou"},
{t:"The Menu",y:2022,k:"m",g:["Horror","Comedy","Thriller"],d:"Mark Mylod"},
{t:"Signs",y:2002,k:"m",g:["Drama","Mystery","Sci-Fi","Thriller"],d:"M. Night Shyamalan"},
{t:"Split",y:2016,k:"m",g:["Horror","Thriller"],d:"M. Night Shyamalan"},
{t:"The Sixth Sense",y:1999,k:"m",g:["Drama","Mystery","Thriller"],d:"M. Night Shyamalan"},
{t:"Deadpool",y:2016,k:"m",g:["Action","Comedy"],d:"Tim Miller"},
{t:"Deadpool & Wolverine",y:2024,k:"m",g:["Action","Comedy","Sci-Fi"],d:"Shawn Levy"},
{t:"Guardians of the Galaxy",y:2014,k:"m",g:["Action","Adventure","Sci-Fi"],d:"James Gunn"},
{t:"The Fall Guy",y:2024,k:"m",g:["Action","Comedy","Romance"],d:"David Leitch"},
{t:"Bullet Train",y:2022,k:"m",g:["Action","Comedy","Thriller"],d:"David Leitch"},
{t:"Free Guy",y:2021,k:"m",g:["Action","Comedy","Sci-Fi"],d:"Shawn Levy"},
{t:"The Nice Guys",y:2016,k:"m",g:["Action","Comedy","Crime"],d:"Shane Black"},
{t:"Kiss Kiss Bang Bang",y:2005,k:"m",g:["Comedy","Crime","Mystery"],d:"Shane Black"},
{t:"Hot Fuzz",y:2007,k:"m",g:["Action","Comedy","Crime"],d:"Edgar Wright"},
{t:"Game Night",y:2018,k:"m",g:["Action","Comedy","Crime"],d:"John Francis Daley"},
{t:"Spy",y:2015,k:"m",g:["Action","Comedy"],d:"Paul Feig"},
{t:"Kingsman: The Secret Service",y:2014,k:"m",g:["Action","Comedy","Adventure"],d:"Matthew Vaughn"},
{t:"21 Jump Street",y:2012,k:"m",g:["Action","Comedy","Crime"],d:"Phil Lord"},
{t:"Tropic Thunder",y:2008,k:"m",g:["Action","Comedy"],d:"Ben Stiller"},
{t:"Dungeons & Dragons: Honor Among Thieves",y:2023,k:"m",g:["Adventure","Fantasy","Comedy"],d:"Jonathan Goldstein"},
{t:"The Princess Bride",y:1987,k:"m",g:["Adventure","Fantasy","Romance"],d:"Rob Reiner"},
{t:"Pirates of the Caribbean: The Curse of the Black Pearl",y:2003,k:"m",g:["Adventure","Fantasy","Action"],d:"Gore Verbinski"},
{t:"National Treasure",y:2004,k:"m",g:["Adventure","Mystery","Action"],d:"Jon Turteltaub"},
{t:"Uncharted",y:2022,k:"m",g:["Adventure","Action"],d:"Ruben Fleischer"},
{t:"Spider-Man: Into the Spider-Verse",y:2018,k:"m",g:["Animation","Action","Adventure"],d:"Bob Persichetti"},
{t:"Spider-Man: Across the Spider-Verse",y:2023,k:"m",g:["Animation","Action","Adventure"],d:"Joaquim Dos Santos"},
{t:"The Incredibles",y:2004,k:"m",g:["Animation","Action","Adventure"],d:"Brad Bird"},
{t:"Coco",y:2017,k:"m",g:["Animation","Family","Fantasy"],d:"Lee Unkrich"},
{t:"Inside Out",y:2015,k:"m",g:["Animation","Family","Comedy"],d:"Pete Docter"},
{t:"How to Train Your Dragon",y:2010,k:"m",g:["Animation","Fantasy","Adventure"],d:"Chris Sanders"},
{t:"The Mitchells vs. the Machines",y:2021,k:"m",g:["Animation","Action","Comedy"],d:"Mike Rianda"},
{t:"Puss in Boots: The Last Wish",y:2022,k:"m",g:["Animation","Adventure","Comedy"],d:"Joel Crawford"},
{t:"The Wild Robot",y:2024,k:"m",g:["Animation","Sci-Fi","Family"],d:"Chris Sanders"},
{t:"Klaus",y:2019,k:"m",g:["Animation","Family","Comedy"],d:"Sergio Pablos"},
{t:"The Dark Knight",y:2008,k:"m",g:["Action","Crime","Drama"],d:"Christopher Nolan"},
{t:"Batman Begins",y:2005,k:"m",g:["Action","Crime","Drama"],d:"Christopher Nolan"},
{t:"Logan",y:2017,k:"m",g:["Action","Drama","Sci-Fi"],d:"James Mangold"},
{t:"The Avengers",y:2012,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Joss Whedon"},
{t:"Captain America: The Winter Soldier",y:2014,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Anthony Russo"},
{t:"Iron Man",y:2008,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Jon Favreau"},
{t:"Thor: Ragnarok",y:2017,k:"m",g:["Action","Adventure","Comedy"],d:"Taika Waititi"},
{t:"Black Panther",y:2018,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Ryan Coogler"},
{t:"Spider-Man: No Way Home",y:2021,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Jon Watts"},
{t:"The Lord of the Rings: The Fellowship of the Ring",y:2001,k:"m",g:["Adventure","Fantasy","Drama"],d:"Peter Jackson"},
{t:"The Lord of the Rings: The Two Towers",y:2002,k:"m",g:["Adventure","Fantasy","Drama"],d:"Peter Jackson"},
{t:"The Lord of the Rings: The Return of the King",y:2003,k:"m",g:["Adventure","Fantasy","Drama"],d:"Peter Jackson"},
{t:"The Fifth Element",y:1997,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Luc Besson"},
{t:"The Patriot",y:2000,k:"m",g:["Drama","History","War"],d:"Roland Emmerich"},
{t:"Rocky",y:1976,k:"m",g:["Drama","Sport"],d:"John G. Avildsen"},
{t:"Creed",y:2015,k:"m",g:["Drama","Sport"],d:"Ryan Coogler"},
{t:"Warrior",y:2011,k:"m",g:["Action","Drama","Sport"],d:"Gavin O'Connor"},
{t:"Rush",y:2013,k:"m",g:["Action","Drama","Sport"],d:"Ron Howard"},
{t:"Moneyball",y:2011,k:"m",g:["Drama","Sport"],d:"Bennett Miller"},
{t:"Whiplash",y:2014,k:"m",g:["Drama","Music"],d:"Damien Chazelle"},
{t:"The Social Network",y:2010,k:"m",g:["Drama"],d:"David Fincher"},
{t:"Se7en",y:1995,k:"m",g:["Crime","Drama","Mystery"],d:"David Fincher"},
{t:"Gone Girl",y:2014,k:"m",g:["Drama","Mystery","Thriller"],d:"David Fincher"},
{t:"Zodiac",y:2007,k:"m",g:["Crime","Drama","Mystery"],d:"David Fincher"},
{t:"The Silence of the Lambs",y:1991,k:"m",g:["Crime","Drama","Thriller"],d:"Jonathan Demme"},
{t:"Heat",y:1995,k:"m",g:["Action","Crime","Drama"],d:"Michael Mann"},
{t:"The Departed",y:2006,k:"m",g:["Crime","Drama","Thriller"],d:"Martin Scorsese"},
{t:"Goodfellas",y:1990,k:"m",g:["Crime","Drama"],d:"Martin Scorsese"},
{t:"The Godfather",y:1972,k:"m",g:["Crime","Drama"],d:"Francis Ford Coppola"},
{t:"Nobody",y:2021,k:"m",g:["Action","Thriller","Crime"],d:"Ilya Naishuller"},
{t:"The Bourne Identity",y:2002,k:"m",g:["Action","Mystery","Thriller"],d:"Doug Liman"},
{t:"Casino Royale",y:2006,k:"m",g:["Action","Adventure","Thriller"],d:"Martin Campbell"},
{t:"Skyfall",y:2012,k:"m",g:["Action","Adventure","Thriller"],d:"Sam Mendes"},
{t:"Mission: Impossible – Fallout",y:2018,k:"m",g:["Action","Adventure","Thriller"],d:"Christopher McQuarrie"},
{t:"The Fugitive",y:1993,k:"m",g:["Action","Crime","Drama"],d:"Andrew Davis"},
{t:"Die Hard",y:1988,k:"m",g:["Action","Thriller"],d:"John McTiernan"},
{t:"Speed",y:1994,k:"m",g:["Action","Adventure","Crime"],d:"Jan de Bont"},
{t:"Twisters",y:2024,k:"m",g:["Action","Adventure","Drama"],d:"Lee Isaac Chung"},
{t:"Civil War",y:2024,k:"m",g:["Action","Drama","War"],d:"Alex Garland"},
{t:"Companion",y:2025,k:"m",g:["Sci-Fi","Thriller","Romance"],d:"Drew Hancock"},
{t:"Her",y:2013,k:"m",g:["Drama","Romance","Sci-Fi"],d:"Spike Jonze"},
{t:"Everything Everywhere All at Once",y:2022,k:"m",g:["Action","Adventure","Sci-Fi"],d:"Daniel Kwan"},
{t:"Breaking Bad",y:2008,k:"tv",g:["Drama","Crime","Thriller"],d:"Vince Gilligan"},
{t:"Better Call Saul",y:2015,k:"tv",g:["Drama","Crime"],d:"Peter Gould"},
{t:"The Wire",y:2002,k:"tv",g:["Crime","Drama","Thriller"],d:"David Simon"},
{t:"True Detective",y:2014,k:"tv",g:["Crime","Drama","Mystery"],d:"Nic Pizzolatto"},
{t:"Fargo",y:2014,k:"tv",g:["Crime","Drama","Thriller"],d:"Noah Hawley"},
{t:"Peaky Blinders",y:2013,k:"tv",g:["Crime","Drama"],d:"Steven Knight"},
{t:"Ozark",y:2017,k:"tv",g:["Crime","Drama","Thriller"],d:"Bill Dubuque"},
{t:"Narcos",y:2015,k:"tv",g:["Crime","Drama","Thriller"],d:"Chris Brancato"},
{t:"The Last of Us",y:2023,k:"tv",g:["Drama","Action","Adventure"],d:"Craig Mazin"},
{t:"Severance",y:2022,k:"tv",g:["Drama","Mystery","Sci-Fi","Thriller"],d:"Dan Erickson"},
{t:"Dark",y:2017,k:"tv",g:["Crime","Drama","Mystery"],d:"Baran bo Odar"},
{t:"Chernobyl",y:2019,k:"tv",g:["Drama","History","Thriller"],d:"Craig Mazin"},
{t:"The Queen's Gambit",y:2020,k:"tv",g:["Drama"],d:"Scott Frank"},
{t:"Succession",y:2018,k:"tv",g:["Drama"],d:"Jesse Armstrong"},
{t:"The Bear",y:2022,k:"tv",g:["Drama","Comedy"],d:"Christopher Storer"},
{t:"Shogun",y:2024,k:"tv",g:["Drama","History","War"],d:"Jonathan van Tulleken"},
{t:"House of the Dragon",y:2022,k:"tv",g:["Action","Drama","Fantasy"],d:"Ryan Condal"},
{t:"The Boys",y:2019,k:"tv",g:["Action","Comedy","Crime"],d:"Eric Kripke"},
{t:"Slow Horses",y:2022,k:"tv",g:["Drama","Thriller","Comedy"],d:"James Hawes"},
{t:"Reacher",y:2022,k:"tv",g:["Action","Crime","Drama"],d:"Nick Santora"},
{t:"The Night Agent",y:2023,k:"tv",g:["Action","Drama","Thriller"],d:"Shawn Ryan"},
{t:"Bodyguard",y:2018,k:"tv",g:["Drama","Thriller","Crime"],d:"Jed Mercurio"},
{t:"Sherlock",y:2010,k:"tv",g:["Crime","Drama","Mystery"],d:"Mark Gatiss"},
{t:"Luther",y:2010,k:"tv",g:["Crime","Drama","Mystery"],d:"Neil Cross"},
{t:"Arcane",y:2021,k:"tv",g:["Animation","Action","Adventure"],d:"Christian Linke"},
{t:"Blue Eye Samurai",y:2023,k:"tv",g:["Animation","Action","Drama"],d:"Michael Green"},
{t:"Scavengers Reign",y:2023,k:"tv",g:["Animation","Drama","Sci-Fi"],d:"Joseph Bennett"},
{t:"Pantheon",y:2022,k:"tv",g:["Animation","Drama","Sci-Fi"],d:"Craig Silverstein"},
{t:"Invincible",y:2021,k:"tv",g:["Animation","Action","Drama"],d:"Robert Kirkman"},
{t:"The Legend of Vox Machina",y:2022,k:"tv",g:["Animation","Action","Adventure"],d:"Brandon Auman"},
{t:"Avatar: The Last Airbender",y:2005,k:"tv",g:["Animation","Action","Adventure"],d:"Michael DiMartino"},
{t:"Game of Thrones",y:2011,k:"tv",g:["Drama","Action","Adventure"],d:"David Benioff"},
{t:"The Witcher",y:2019,k:"tv",g:["Action","Adventure","Drama"],d:"Lauren Schmidt Hissrich"},
{t:"The Mandalorian",y:2019,k:"tv",g:["Action","Adventure","Sci-Fi"],d:"Jon Favreau"},
{t:"Andor",y:2022,k:"tv",g:["Action","Adventure","Drama"],d:"Tony Gilroy"},
{t:"Fallout",y:2024,k:"tv",g:["Drama","Sci-Fi","Action"],d:"Geneva Robertson-Dworet"},
{t:"Silo",y:2023,k:"tv",g:["Drama","Mystery","Sci-Fi"],d:"Graham Yost"},
{t:"From",y:2022,k:"tv",g:["Drama","Horror","Mystery"],d:"John Griffin"},
{t:"Stranger Things",y:2016,k:"tv",g:["Drama","Fantasy","Mystery"],d:"Matt Duffer"},
{t:"The Office",y:2005,k:"tv",g:["Comedy"],d:"Greg Daniels"},
{t:"Parks and Recreation",y:2009,k:"tv",g:["Comedy"],d:"Greg Daniels"},
{t:"Brooklyn Nine-Nine",y:2013,k:"tv",g:["Comedy","Crime"],d:"Dan Goor"},
{t:"The Good Place",y:2016,k:"tv",g:["Comedy","Drama","Fantasy"],d:"Michael Schur"},
{t:"Ted Lasso",y:2020,k:"tv",g:["Comedy","Drama","Sport"],d:"Jason Sudeikis"},
{t:"What We Do in the Shadows",y:2019,k:"tv",g:["Comedy","Fantasy","Horror"],d:"Jemaine Clement"},
{t:"Abbott Elementary",y:2021,k:"tv",g:["Comedy"],d:"Quinta Brunson"},
{t:"Band of Brothers",y:2001,k:"tv",g:["Drama","History","War"],d:"Tom Hanks"},
{t:"The Pacific",y:2010,k:"tv",g:["Drama","History","War"],d:"Bruce C. McKenna"},
{t:"Masters of the Air",y:2024,k:"tv",g:["Drama","History","War"],d:"John Shiban"},
{t:"Yellowstone",y:2018,k:"tv",g:["Drama","Western"],d:"Taylor Sheridan"}
];
if (typeof module !== "undefined") module.exports = CATALOG;
